version: "3.9"

services:
  web2204-php7:
    build:
      context: .
      dockerfile: ./2204/Dockerfile
      args:
        - PHP_VERSION=7.4
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3030:80"
      - "3031:3306"
    tmpfs:
      - /var/lib/mysql

  web2204-php8:
    build:
      context: .
      dockerfile: ./2204/Dockerfile
      args:
        - PHP_VERSION=8.0
    environment:
      - MYSQL_ADMIN_PASS=password
    ports:
      - "3040:80"
      - "3041:3306"
    tmpfs:
      - /var/lib/mysql
